// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6XdzS2Odp5wnFqMHqvLUTffxCDopiahA',
    appId: '1:145617815315:web:2d68cfae2991180b07fce6',
    messagingSenderId: '145617815315',
    projectId: 'flutter-flight-booking-ba668',
    authDomain: 'flutter-flight-booking-ba668.firebaseapp.com',
    storageBucket: 'flutter-flight-booking-ba668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNkcAIRimqFWVDx2G7t7uIvrdllCo0hSE',
    appId: '1:145617815315:android:ea2e9369816404fd07fce6',
    messagingSenderId: '145617815315',
    projectId: 'flutter-flight-booking-ba668',
    storageBucket: 'flutter-flight-booking-ba668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0BSpB7P6WsWREGyj8VBvHwrNS8d9yhE',
    appId: '1:145617815315:ios:28ff380d431e86e807fce6',
    messagingSenderId: '145617815315',
    projectId: 'flutter-flight-booking-ba668',
    storageBucket: 'flutter-flight-booking-ba668.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlightBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0BSpB7P6WsWREGyj8VBvHwrNS8d9yhE',
    appId: '1:145617815315:ios:28ff380d431e86e807fce6',
    messagingSenderId: '145617815315',
    projectId: 'flutter-flight-booking-ba668',
    storageBucket: 'flutter-flight-booking-ba668.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlightBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6XdzS2Odp5wnFqMHqvLUTffxCDopiahA',
    appId: '1:145617815315:web:fa6707712cbc8cd607fce6',
    messagingSenderId: '145617815315',
    projectId: 'flutter-flight-booking-ba668',
    authDomain: 'flutter-flight-booking-ba668.firebaseapp.com',
    storageBucket: 'flutter-flight-booking-ba668.firebasestorage.app',
  );
}
